### PR TITLE
Add a `.chromeDataDir` option to help debugging tests

### PR DESCRIPTION
**Pull request by songawee**
This option is useful when running tests in a non-headless Chrome environment. This will allow Chrome to save user preferences between test runs. For example, one thing I often get frustrated with is that Chrome never remembers where I last left the Chrome Dev Tools. With this change, it will be in the same spot upon returning to debug tests. This also applies to other user preferences as well.

I left it as an "opt-in" rather than a default to avoid folks forgetting to add the datadir to their `.gitignore` file.

I also had trouble installing this package locally. I kept getting a `Plugin 'jsx' not found`. I'm happy to further test or improve this pr.

Thanks for this awesome tool!

### CODE REVIEW

**Comment by developit** [comment]
What version of node + npm are you running?  I've been getting the jsx issue thing on travis and could use any additional information.

**Comment by songawee** [comment]
Sure, my env info is:
- node 8.6.0
- npm 5.3.0

I have also tried:
- node 9.3.0
- npm 5.5.1

My guess is that the problem is a dependency shift? I haven't been able to figure out what exactly is missing the plugin either. Could be babel missing the plugin or perhaps the bundler.

**Comment by songawee** [comment]
screen shot 2018-01-24 at 1 04 39 pm

Ok, was able to repro (I think). I `npm link`ed mircobundle and then I placed a `null` in microbundle here - https://github.com/developit/microbundle/blob/master/src/index.js#L229. Then placed a `console.log` here - https://github.com/developit/microbundle/blob/master/src/cli.js#L50. 

Hope that helps debug.

**Comment by developit** [comment]
Awesome, thanks @songawee that really does help!

**Comment by developit** [comment]
The build error should be fixed in [the latest microbundle](https://github.com/developit/microbundle/releases/tag/0.4.2).

**Comment by songawee** [comment]
Thanks for your help with this! Maybe we could try deleting the travis cache to see if that pulls in the fixed dep? - https://docs.travis-ci.com/user/caching/#Clearing-Caches. I've had success with that in circleci. ¯\_(ツ)_/¯

**Comment by developit** [comment]
Strangely, no caches are listed :/

**Comment by developit** [comment]
Released in [2.0.0](https://github.com/developit/karmatic/releases/tag/2.0.0).

**Pull request merged**
